import {
    HomePage,
    AboutPage,
    NewsPage,
    EventsPage,
    ContactusPage,
    HemorrhagicPage,
    ProjectsPage,
    LibraryPage,
    PostPage,
    SearchPage,
    MultimediaPage,
    ManageDashboard,
    ManagePosts,
    ManagePost,
    ManageEditPost,
    ManageNavigations,
    ManageNavigation,
    ManageSponsors,
    ManageSponsor,
    ManageEditSponsor,
    RegisterPage,
    ManageManagements,
    ManageManagement,
    ManageEditManagement,
    ManagementPage
} from "../pages";

import AuthPage from "../pages/auth/auth";


export const adminRoutes = [
    {path: '/dashboard', component: <ManageDashboard/>, exact: true},
    {path: '/posts', component: <ManagePosts/>, exact: true},
    {path: '/post', component: <ManagePost/>, exact: true},
    {path: '/post/:id', component: <ManageEditPost/>, exact: true},
    {path: '/sponsors', component: <ManageSponsors/>, exact: true},
    {path: '/sponsor', component: <ManageSponsor/>, exact: true},
    {path: '/sponsor/:id', component: <ManageEditSponsor/>, exact: true},
    {path: '/navigations', component: <ManageNavigations/>, exact: true},
    {path: '/navigation', component: <ManageNavigation/>, exact: true},
    {path: '/navigation/:id', component: <ManageNavigation/>, exact: true},
    {path: '/managements', component: <ManageManagements/>, exact: true},
    {path: '/management', component: <ManageManagement/>, exact: true},
    {path: '/management/:id', component: <ManageEditManagement/>, exact: true},
];

export const publicRoutes = [
    {path: "/", component: <HomePage/>, exact: true},
    {path: "/home/:lang", component: <HomePage/>, exact: true},
    {path: "/aboutus/:lang", component: <AboutPage/>, exact: true},
    {path: "/aboutus/:lang/:subcategory", component: <AboutPage/>, exact: true},
    {path: '/management/:id', component: <ManagementPage/>, exact: true},
    {path: "/news/:lang", component: <NewsPage/>, exact: true},
    {path: "/events/:lang", component: <EventsPage/>, exact: true},
    {path: "/events/:lang/:subcategory", component: <EventsPage/>, exact: true},
    {path: "/projects/:lang", component: <ProjectsPage/>, exact: true},
    {path: "/projects/:lang/:subcategory", component: <ProjectsPage/>, exact: true},
    {path: "/hemorrhagicdiseases/:lang", component: <HemorrhagicPage/>, exact: true},
    {path: "/contactus/:lang", component: <ContactusPage/>, exact: true},
    {path: "/library/:lang", component: <LibraryPage/>, exact: true},
    {path: "/library/:lang/:subcategory", component: <LibraryPage/>, exact: true},
    {path: "/multimedia/:lang", component: <MultimediaPage/>, exact: true},
    {path: "/multimedia/:lang/:subcategory", component: <MultimediaPage/>, exact: true},
    {path: '/post', component: <PostPage/>, exact: true},
    {path: '/post/:id', component: <PostPage/>, exact: true},
    {path: '/search', component: <SearchPage/>, exact: true},
    {path: "/auth", component: <AuthPage/>, exact: true},
    {path: "/register", component: <RegisterPage/>, exact: true},
];
